steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase-staging', 'cloud_build/staging_container']
images:
- 'gcr.io/$PROJECT_ID/firebase-staging'
tags: ['dash-firebase-staging']
