name: site_shared
publish_to: none
repository: https://github.com/dart-lang/site-shared
description: >-
  Archived workspace for packages previously used by
  the Dart and Flutter documentation sites.
  Most packages have been deprecated or are now
  maintained in the flutter/website repository.

environment:
  sdk: ^3.9.0

workspace:
  - pkgs/analysis_defaults
  - pkgs/dash_design
  - pkgs/excerpter
  - pkgs/inject_dartpad
