name: analysis_defaults
description: Analysis defaults for Dart/Flutter site tools
publish_to: none

environment:
  sdk: ^3.0.0

# NOTE: Code is not allowed in this package. Do not add dependencies.
dependencies:
  dart_flutter_team_lints: ^1.0.0
