name: excerpter
description: Update code excerpts in Markdown documentation from source files.
version: 0.1.0
publish_to: none
repository: https://github.com/dart-lang/site-shared/tree/main/packages/excerpter

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  file: ^7.0.0
  glob: ^2.1.2
  meta: ^1.14.0
  path: ^1.9.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  io: ^1.0.4
  test: ^1.25.2

executables:
  excerpter: excerpter
